/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.32
 * Generated at: 2023-12-06 06:59:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/view/../common/head.jsp", Long.valueOf(1701390492539L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v6.1.2/css/all.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\" crossorigin=\"anonymous\"></script>");
      out.write("\r\n");
      out.write("<title>神田英会話スクール</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"d-flex justify-content-end align-items-center my-3\">\r\n");
      out.write("\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/view/home.jsp\"\r\n");
      out.write("\t\t\tstyle=\"margin-right: auto;\"\r\n");
      out.write("\t\t\tclass=\"text-decoration-none text-reset fs-5 ms-3\">\r\n");
      out.write("\t\t\t<i class=\"fa-solid fa-graduation-cap\"></i> 神田英会話スクール</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/view/inquiry.jsp\" class=\"btn btn-primary\">お問い合わせ</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/view/login.jsp\" class=\"btn btn-primary mx-2\">管理者ログイン</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"d-flex justify-content-center align-items-center\"\r\n");
      out.write("\t\tstyle=\"background-image: url(images/banner.jpg); height: 600px; background-size: cover; background-position: 50% 50%;\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<h1 class=\"text-light \" style=\"text-shadow: 0 0 3px rgba(0, 0, 0, 0.8);\">神田英会話スクール</h1>\r\n");
      out.write("\t\t\t<p class=\"text-light\" style=\"text-shadow: 0 0 3px rgba(0, 0, 0, 0.8);\">自分に合ったコンテンツで楽しく英会話を学ぶ</p>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/view/inquiry.jsp\" class=\"btn btn-primary shadow\">お問い合わせ</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<h3 class=\"text-decoration-underline my-3\">仕組み</h3>\r\n");
      out.write("\t\t<div class=\"row row-cols-1 row-cols-md-3 g-4\">\r\n");
      out.write("\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t<div class=\"card h-100\">\r\n");
      out.write("\t\t\t\t\t<div class=\"fs-1 ps-3\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa-regular fa-file-lines\"></i>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"card-title\">アセスメント</h5>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">経験豊富な講師が、会話、リスニング、読解、ライティングのスキルを評価します。\r\n");
      out.write("\t\t\t\t\t\t\tこのアセスメントにより、学習ニーズを把握し、あなたのレベルに合わせたプログラムを提供します。</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t<div class=\"card h-100\">\r\n");
      out.write("\t\t\t\t\t<div class=\"fs-1 ps-3\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa-regular fa-pen-to-square\"></i>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"card-title\">パーソナライズされた学習プラン</h5>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">アセスメントの結果を基に、パーソナライズされた学習プランを作成します。\r\n");
      out.write("\t\t\t\t\t\t\tあなたの目標に合わせた具体的な目標、改善すべきポイント、おすすめのコース期間が含まれます。\r\n");
      out.write("\t\t\t\t\t\t\t効果的かつ効率的な学習を実現するために、カスタマイズされたアプローチを採用しています。</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t<div class=\"card h-100\">\r\n");
      out.write("\t\t\t\t\t<div class=\"fs-1 ps-3\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa-regular fa-calendar\"></i>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"card-title\">柔軟なスケジュール</h5>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">自分の都合や学習スタイルに合わせたスケジュールを選択できます。\r\n");
      out.write("\t\t\t\t\t\t\t午前、午後、夜のクラスなど、柔軟なオプションを提供しています。\r\n");
      out.write("\t\t\t\t\t\t\t学習のペースと都合に合わせて、レッスンの頻度と時間を選ぶことができます。</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t<div class=\"card h-100\">\r\n");
      out.write("\t\t\t\t\t<div class=\"fs-1 ps-3\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa-solid fa-school\"></i>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"card-title\">豊富な学習資料</h5>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">レッスンプラン、音声録音、インタラクティブな演習など、さまざまな学習資料にアクセスできます。\r\n");
      out.write("\t\t\t\t\t\t\t広範なトピック、文法、語彙、発音などをカバーしています。 ライブクラスに補完するために、自習資料を活用して学習を強化できます。</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t<div class=\"card h-100\">\r\n");
      out.write("\t\t\t\t\t<div class=\"fs-1 ps-3\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa-solid fa-bars-progress\"></i>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"card-title\">進捗の追跡</h5>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">定期的なアセスメントや講師からのフィードバックにより、進捗を確認できます。\r\n");
      out.write("\t\t\t\t\t\t\tスピーキング、リスニング、読解、ライティングのスキルの向上を時間の経過とともに追跡します。\r\n");
      out.write("\t\t\t\t\t\t\t言語の目標達成をサポートするために、講師がガイダンスとサポートを提供します。</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t<div class=\"card h-100\">\r\n");
      out.write("\t\t\t\t\t<div class=\"fs-1 ps-3\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa-solid fa-headset\"></i>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"card-title\">継続的なサポート</h5>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">学習の旅を通じてサポートを提供する専任のサポートチームがいます。\r\n");
      out.write("\t\t\t\t\t\t\t質問や技術的な問題、追加のサポートが必要な場合は、いつでもお問い合わせください。</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<div class=\"mb-3 text-center\">Copyright © 神田英会話スクール</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
